export const ERROR = {
  DUPLICATE_KID_NAME: 'DUPLICATE_KID_NAME',
  INVALID_NAME_CHARS: 'INVALID_NAME_CHARS',
  TOO_MANY_KIDS: 'TOO_MANY_KIDS',
  ACTIVATION_CODE_NOT_FOUND: 'ACTIVATION_CODE_NOT_FOUND',
  ACTIVATION_CODE_EXPIRED: 'ACTIVATION_CODE_EXPIRED',
  ACTIVATION_CODE_ALREADY_USED: 'ACTIVATION_CODE_ALREADY_USED',
};
