/**
 * Copy from: https://github.com/emotion-js/emotion/tree/26ded6109fcd8ca9875cc2ce4564fee678a3f3c5/packages/is-prop-valid/src
 * License: (MIT) https://github.com/emotion-js/emotion/blob/main/LICENSE
 * The reason for not importing directly from third-party libraries(emotion/storybook) is to avoid tree shaking fails
 */
function memoize(fn) {
    var cache = {};
    return function (arg) {
        if (cache[arg] === undefined)
            cache[arg] = fn(arg);
        return cache[arg];
    };
}
// const props = {
//   // react props
//   // https://github.com/facebook/react/blob/5495a7f24aef85ba6937truetrue1ce962673ca9f5fde6/src/renderers/dom/shared/hooks/ReactDOMUnknownPropertyHook.js
//   children: true,
//   dangerouslySetInnerHTML: true,
//   key: true,
//   ref: true,
//   autoFocus: true,
//   defaultValue: true,
//   defaultChecked: true,
//   innerHTML: true,
//   suppressContentEditableWarning: true,
//   suppressHydrationWarning: true,
//   // deprecated react prop
//   valueLink: true,
//
//   // https://github.com/facebook/react/blob/d7157651f7b72d9888ctrue123e191f9b88cd8f41e9/src/renderers/dom/shared/HTMLDOMPropertyConfig.js
//   /**
//    * Standard Properties
//    */
//
//   accept: true,
//   acceptCharset: true,
//   accessKey: true,
//   action: true,
//   allow: true,
//   allowUserMedia: true,
//   allowPaymentRequest: true,
//   allowFullScreen: true,
//   allowTransparency: true,
//   alt: true,
//   // specifies target context for links with `preload` type
//   // as: true,
//   async: true,
//   autoComplete: true,
//   // autoFocus is polyfilled/normalized by AutoFocusUtils
//   // autoFocus: true,
//   autoPlay: true,
//   capture: true,
//   cellPadding: true,
//   cellSpacing: true,
//   // keygen prop
//   challenge: true,
//   charSet: true,
//   checked: true,
//   cite: true,
//   classID: true,
//   className: true,
//   cols: true,
//   colSpan: true,
//   content: true,
//   contentEditable: true,
//   contextMenu: true,
//   controls: true,
//   controlsList: true,
//   coords: true,
//   crossOrigin: true,
//   data: true, // For `<object />` acts as `src`.
//   dateTime: true,
//   decoding: true,
//   default: true,
//   defer: true,
//   dir: true,
//   disabled: true,
//   disablePictureInPicture: true,
//   download: true,
//   draggable: true,
//   encType: true,
//   form: true,
//   formAction: true,
//   formEncType: true,
//   formMethod: true,
//   formNoValidate: true,
//   formTarget: true,
//   frameBorder: true,
//   headers: true,
//   height: true,
//   hidden: true,
//   high: true,
//   href: true,
//   hrefLang: true,
//   htmlFor: true,
//   httpEquiv: true,
//   id: true,
//   inputMode: true,
//   integrity: true,
//   is: true,
//   keyParams: true,
//   keyType: true,
//   kind: true,
//   label: true,
//   lang: true,
//   list: true,
//   loading: true,
//   loop: true,
//   low: true,
//   // manifest: true,
//   marginHeight: true,
//   marginWidth: true,
//   max: true,
//   maxLength: true,
//   media: true,
//   mediaGroup: true,
//   method: true,
//   min: true,
//   minLength: true,
//   // Caution; `option.selected` is not updated if `select.multiple` is
//   // disabled with `removeAttribute`.
//   multiple: true,
//   muted: true,
//   name: true,
//   nonce: true,
//   noValidate: true,
//   open: true,
//   optimum: true,
//   pattern: true,
//   placeholder: true,
//   playsInline: true,
//   poster: true,
//   preload: true,
//   profile: true,
//   radioGroup: true,
//   readOnly: true,
//   referrerPolicy: true,
//   rel: true,
//   required: true,
//   reversed: true,
//   role: true,
//   rows: true,
//   rowSpan: true,
//   sandbox: true,
//   scope: true,
//   scoped: true,
//   scrolling: true,
//   seamless: true,
//   selected: true,
//   shape: true,
//   size: true,
//   sizes: true,
//   // support for projecting regular DOM Elements via V1 named slots ( shadow dom )
//   slot: true,
//   span: true,
//   spellCheck: true,
//   src: true,
//   srcDoc: true,
//   srcLang: true,
//   srcSet: true,
//   start: true,
//   step: true,
//   style: true,
//   summary: true,
//   tabIndex: true,
//   target: true,
//   title: true,
//   // Setting .type throws on non-<input> tags
//   type: true,
//   useMap: true,
//   value: true,
//   width: true,
//   wmode: true,
//   wrap: true,
//
//   /**
//    * RDFa Properties
//    */
//   about: true,
//   datatype: true,
//   inlist: true,
//   prefix: true,
//   // property is also supported for OpenGraph in meta tags.
//   property: true,
//   resource: true,
//   typeof: true,
//   vocab: true,
//
//   /**
//    * Non-standard Properties
//    */
//   // autoCapitalize and autoCorrect are supported in Mobile Safari for
//   // keyboard hints.
//   autoCapitalize: true,
//   autoCorrect: true,
//   // autoSave allows WebKit/Blink to persist values of input fields on page reloads
//   autoSave: true,
//   // color is for Safari mask-icon link
//   color: true,
//   // https://html.spec.whatwg.org/multipage/interaction.html#inert
//   inert: true,
//   // itemProp, itemScope, itemType are for
//   // Microdata support. See http://schema.org/docs/gs.html
//   itemProp: true,
//   itemScope: true,
//   itemType: true,
//   // itemID and itemRef are for Microdata support as well but
//   // only specified in the WHATWG spec document. See
//   // https://html.spec.whatwg.org/multipage/microdata.html#microdata-dom-api
//   itemID: true,
//   itemRef: true,
//   // used in amp html for eventing purposes
//   on: true,
//   // results show looking glass icon and recent searches on input
//   // search fields in WebKit/Blink
//   results: true,
//   // IE-only attribute that specifies security restrictions on an iframe
//   // as an alternative to the sandbox attribute on IE<1true
//   security: true,
//   // IE-only attribute that controls focus behavior
//   unselectable: true,
//   //
//   // SVG properties: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
//   // The following "onX" events have been omitted:
//   //
//   //  onabort
//   //  onactivate
//   //  onbegin
//   //  onclick
//   //  onend
//   //  onerror
//   //  onfocusin
//   //  onfocusout
//   //  onload
//   //  onmousedown
//   //  onmousemove
//   //  onmouseout
//   //  onmouseover
//   //  onmouseup
//   //  onrepeat
//   //  onresize
//   //  onscroll
//   //  onunload
//   accentHeight: true,
//   accumulate: true,
//   additive: true,
//   alignmentBaseline: true,
//   allowReorder: true,
//   alphabetic: true,
//   amplitude: true,
//   arabicForm: true,
//   ascent: true,
//   attributeName: true,
//   attributeType: true,
//   autoReverse: true,
//   azimuth: true,
//   baseFrequency: true,
//   baselineShift: true,
//   baseProfile: true,
//   bbox: true,
//   begin: true,
//   bias: true,
//   by: true,
//   calcMode: true,
//   capHeight: true,
//   clip: true,
//   clipPathUnits: true,
//   clipPath: true,
//   clipRule: true,
//   colorInterpolation: true,
//   colorInterpolationFilters: true,
//   colorProfile: true,
//   colorRendering: true,
//   contentScriptType: true,
//   contentStyleType: true,
//   cursor: true,
//   cx: true,
//   cy: true,
//   d: true,
//   decelerate: true,
//   descent: true,
//   diffuseConstant: true,
//   direction: true,
//   display: true,
//   divisor: true,
//   dominantBaseline: true,
//   dur: true,
//   dx: true,
//   dy: true,
//   edgeMode: true,
//   elevation: true,
//   enableBackground: true,
//   end: true,
//   exponent: true,
//   externalResourcesRequired: true,
//   fill: true,
//   fillOpacity: true,
//   fillRule: true,
//   filter: true,
//   filterRes: true,
//   filterUnits: true,
//   floodColor: true,
//   floodOpacity: true,
//   focusable: true,
//   fontFamily: true,
//   fontSize: true,
//   fontSizeAdjust: true,
//   fontStretch: true,
//   fontStyle: true,
//   fontVariant: true,
//   fontWeight: true,
//   format: true,
//   from: true,
//   fr: true, // valid SVG element but React will ask for removal
//   fx: true,
//   fy: true,
//   g1: true,
//   g2: true,
//   glyphName: true,
//   glyphOrientationHorizontal: true,
//   glyphOrientationVertical: true,
//   glyphRef: true,
//   gradientTransform: true,
//   gradientUnits: true,
//   hanging: true,
//   horizAdvX: true,
//   horizOriginX: true,
//   ideographic: true,
//   imageRendering: true,
//   in: true,
//   in2: true,
//   intercept: true,
//   k: true,
//   k1: true,
//   k2: true,
//   k3: true,
//   k4: true,
//   kernelMatrix: true,
//   kernelUnitLength: true,
//   kerning: true,
//   keyPoints: true,
//   keySplines: true,
//   keyTimes: true,
//   lengthAdjust: true,
//   letterSpacing: true,
//   lightingColor: true,
//   limitingConeAngle: true,
//   local: true,
//   markerEnd: true,
//   markerMid: true,
//   markerStart: true,
//   markerHeight: true,
//   markerUnits: true,
//   markerWidth: true,
//   mask: true,
//   maskContentUnits: true,
//   maskUnits: true,
//   mathematical: true,
//   mode: true,
//   numOctaves: true,
//   offset: true,
//   opacity: true,
//   operator: true,
//   order: true,
//   orient: true,
//   orientation: true,
//   origin: true,
//   overflow: true,
//   overlinePosition: true,
//   overlineThickness: true,
//   panose1: true,
//   paintOrder: true,
//   pathLength: true,
//   patternContentUnits: true,
//   patternTransform: true,
//   patternUnits: true,
//   pointerEvents: true,
//   points: true,
//   pointsAtX: true,
//   pointsAtY: true,
//   pointsAtZ: true,
//   preserveAlpha: true,
//   preserveAspectRatio: true,
//   primitiveUnits: true,
//   r: true,
//   radius: true,
//   refX: true,
//   refY: true,
//   renderingIntent: true,
//   repeatCount: true,
//   repeatDur: true,
//   requiredExtensions: true,
//   requiredFeatures: true,
//   restart: true,
//   result: true,
//   rotate: true,
//   rx: true,
//   ry: true,
//   scale: true,
//   seed: true,
//   shapeRendering: true,
//   slope: true,
//   spacing: true,
//   specularConstant: true,
//   specularExponent: true,
//   speed: true,
//   spreadMethod: true,
//   startOffset: true,
//   stdDeviation: true,
//   stemh: true,
//   stemv: true,
//   stitchTiles: true,
//   stopColor: true,
//   stopOpacity: true,
//   strikethroughPosition: true,
//   strikethroughThickness: true,
//   string: true,
//   stroke: true,
//   strokeDasharray: true,
//   strokeDashoffset: true,
//   strokeLinecap: true,
//   strokeLinejoin: true,
//   strokeMiterlimit: true,
//   strokeOpacity: true,
//   strokeWidth: true,
//   surfaceScale: true,
//   systemLanguage: true,
//   tableValues: true,
//   targetX: true,
//   targetY: true,
//   textAnchor: true,
//   textDecoration: true,
//   textRendering: true,
//   textLength: true,
//   to: true,
//   transform: true,
//   u1: true,
//   u2: true,
//   underlinePosition: true,
//   underlineThickness: true,
//   unicode: true,
//   unicodeBidi: true,
//   unicodeRange: true,
//   unitsPerEm: true,
//   vAlphabetic: true,
//   vHanging: true,
//   vIdeographic: true,
//   vMathematical: true,
//   values: true,
//   vectorEffect: true,
//   version: true,
//   vertAdvY: true,
//   vertOriginX: true,
//   vertOriginY: true,
//   viewBox: true,
//   viewTarget: true,
//   visibility: true,
//   widths: true,
//   wordSpacing: true,
//   writingMode: true,
//   x: true,
//   xHeight: true,
//   x1: true,
//   x2: true,
//   xChannelSelector: true,
//   xlinkActuate: true,
//   xlinkArcrole: true,
//   xlinkHref: true,
//   xlinkRole: true,
//   xlinkShow: true,
//   xlinkTitle: true,
//   xlinkType: true,
//   xmlBase: true,
//   xmlns: true,
//   xmlnsXlink: true,
//   xmlLang: true,
//   xmlSpace: true,
//   y: true,
//   y1: true,
//   y2: true,
//   yChannelSelector: true,
//   z: true,
//   zoomAndPan: true,
//   // preact
//   for: true,
//   class: true,
//   autofocus: true,
// };
/**
 * This is generated from by `/^((${Object.keys(props).join('|')})|(([Dd][Aa][Tt][Aa]|[Aa][Rr][Ii][Aa]|x)-.*))$/`
 * for better performance
 */
var reactPropsRegex = /^((children|dangerouslySetInnerHTML|key|ref|autoFocus|defaultValue|defaultChecked|innerHTML|suppressContentEditableWarning|suppressHydrationWarning|valueLink|accept|acceptCharset|accessKey|action|allow|allowUserMedia|allowPaymentRequest|allowFullScreen|allowTransparency|alt|async|autoComplete|autoPlay|capture|cellPadding|cellSpacing|challenge|charSet|checked|cite|classID|className|cols|colSpan|content|contentEditable|contextMenu|controls|controlsList|coords|crossOrigin|data|dateTime|decoding|default|defer|dir|disabled|disablePictureInPicture|download|draggable|encType|form|formAction|formEncType|formMethod|formNoValidate|formTarget|frameBorder|headers|height|hidden|high|href|hrefLang|htmlFor|httpEquiv|id|inputMode|integrity|is|keyParams|keyType|kind|label|lang|list|loading|loop|low|marginHeight|marginWidth|max|maxLength|media|mediaGroup|method|min|minLength|multiple|muted|name|nonce|noValidate|open|optimum|pattern|placeholder|playsInline|poster|preload|profile|radioGroup|readOnly|referrerPolicy|rel|required|reversed|role|rows|rowSpan|sandbox|scope|scoped|scrolling|seamless|selected|shape|size|sizes|slot|span|spellCheck|src|srcDoc|srcLang|srcSet|start|step|style|summary|tabIndex|target|title|type|useMap|value|width|wmode|wrap|about|datatype|inlist|prefix|property|resource|typeof|vocab|autoCapitalize|autoCorrect|autoSave|color|inert|itemProp|itemScope|itemType|itemID|itemRef|on|results|security|unselectable|accentHeight|accumulate|additive|alignmentBaseline|allowReorder|alphabetic|amplitude|arabicForm|ascent|attributeName|attributeType|autoReverse|azimuth|baseFrequency|baselineShift|baseProfile|bbox|begin|bias|by|calcMode|capHeight|clip|clipPathUnits|clipPath|clipRule|colorInterpolation|colorInterpolationFilters|colorProfile|colorRendering|contentScriptType|contentStyleType|cursor|cx|cy|d|decelerate|descent|diffuseConstant|direction|display|divisor|dominantBaseline|dur|dx|dy|edgeMode|elevation|enableBackground|end|exponent|externalResourcesRequired|fill|fillOpacity|fillRule|filter|filterRes|filterUnits|floodColor|floodOpacity|focusable|fontFamily|fontSize|fontSizeAdjust|fontStretch|fontStyle|fontVariant|fontWeight|format|from|fr|fx|fy|g1|g2|glyphName|glyphOrientationHorizontal|glyphOrientationVertical|glyphRef|gradientTransform|gradientUnits|hanging|horizAdvX|horizOriginX|ideographic|imageRendering|in|in2|intercept|k|k1|k2|k3|k4|kernelMatrix|kernelUnitLength|kerning|keyPoints|keySplines|keyTimes|lengthAdjust|letterSpacing|lightingColor|limitingConeAngle|local|markerEnd|markerMid|markerStart|markerHeight|markerUnits|markerWidth|mask|maskContentUnits|maskUnits|mathematical|mode|numOctaves|offset|opacity|operator|order|orient|orientation|origin|overflow|overlinePosition|overlineThickness|panose1|paintOrder|pathLength|patternContentUnits|patternTransform|patternUnits|pointerEvents|points|pointsAtX|pointsAtY|pointsAtZ|preserveAlpha|preserveAspectRatio|primitiveUnits|r|radius|refX|refY|renderingIntent|repeatCount|repeatDur|requiredExtensions|requiredFeatures|restart|result|rotate|rx|ry|scale|seed|shapeRendering|slope|spacing|specularConstant|specularExponent|speed|spreadMethod|startOffset|stdDeviation|stemh|stemv|stitchTiles|stopColor|stopOpacity|strikethroughPosition|strikethroughThickness|string|stroke|strokeDasharray|strokeDashoffset|strokeLinecap|strokeLinejoin|strokeMiterlimit|strokeOpacity|strokeWidth|surfaceScale|systemLanguage|tableValues|targetX|targetY|textAnchor|textDecoration|textRendering|textLength|to|transform|u1|u2|underlinePosition|underlineThickness|unicode|unicodeBidi|unicodeRange|unitsPerEm|vAlphabetic|vHanging|vIdeographic|vMathematical|values|vectorEffect|version|vertAdvY|vertOriginX|vertOriginY|viewBox|viewTarget|visibility|widths|wordSpacing|writingMode|x|xHeight|x1|x2|xChannelSelector|xlinkActuate|xlinkArcrole|xlinkHref|xlinkRole|xlinkShow|xlinkTitle|xlinkType|xmlBase|xmlns|xmlnsXlink|xmlLang|xmlSpace|y|y1|y2|yChannelSelector|z|zoomAndPan|for|class|autofocus)|(([Dd][Aa][Tt][Aa]|[Aa][Rr][Ii][Aa]|x)-.*))$/;
export default memoize(function (prop) {
    return reactPropsRegex.test(prop)
        || (prop.charCodeAt(0) === 111
            && /* o */ prop.charCodeAt(1) === 110
            && /* n */ prop.charCodeAt(2) < 91);
} /* Z+1 */);
//# sourceMappingURL=isPropValid.js.map